name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 go build -o iwmon.exe -v -ldflags "-s -w" ./...
        GOOS=linux GOARCH=amd64 go build -o iwmon -v -ldflags "-s -w" ./...

    - name: Test
      run: go test -v ./...

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v2
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          ./iwmon.exe
          ./iwmon